### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by kirsikkahiltunen** [tapsamies/Tsoha-keskustelusovellus#1]
Työ on hyvässä vauhdissa. Sovellusta pystyy testaamaan fly.io:ssa sekä paikallisesti omalla tietokoneella. Sovelluksen käyttö on intuitiivista. Rekisteröityminen ja kirjautuminen toimii oletetusti. Koodi on johdonmukaista ja helppolukuista, muuttujat ja eri kooditiedostot on nimetty kuvaavasti. Tietokannan rakenne vaikuttaa keskustelusovelluksen toteuttamiseen sopivalta; taulut ”visitors”, ”users”, ”categories”, ”threads” ja ”messages” löytyy. 
Index.html tiedoston koodia voisi muokata niin, ettei ”Kirjaudu ulos”, ”Uusi viesti”, ”Yleinen keskustelualue” ja ”keskustelualueet” tekstit olisi sijoiteltu näin peräkkäin, jotta sivu olisi ulkoasultaan selkeämpi ja valintojen luettavuus olisi parempi. Muuten sovellus näyttää olevan jo hyvä luonnos keskustelusovelluksesta. Hyvää työtä!

**Comment by tapsamies** [comment]
Kiitos hyvästä palautteesta ja kehitysideoista!
